# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'console.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Console(object):
    def setupUi(self, Console):
        Console.setObjectName("Console")
        Console.resize(1050, 741)
        self.ConsoleWidget_con = ConsoleWidget(Console)
        self.ConsoleWidget_con.setGeometry(QtCore.QRect(10, 110, 681, 621))
        self.ConsoleWidget_con.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ConsoleWidget_con.setObjectName("ConsoleWidget_con")
        self.TabWidget_data = QtWidgets.QTabWidget(Console)
        self.TabWidget_data.setGeometry(QtCore.QRect(710, 120, 311, 501))
        self.TabWidget_data.setObjectName("TabWidget_data")
        self.tab_ticker = QtWidgets.QWidget()
        self.tab_ticker.setObjectName("tab_ticker")
        self.TableWidget_tickers = QtWidgets.QTableWidget(self.tab_ticker)
        self.TableWidget_tickers.setGeometry(QtCore.QRect(0, 10, 301, 451))
        self.TableWidget_tickers.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TableWidget_tickers.setAutoScroll(False)
        self.TableWidget_tickers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TableWidget_tickers.setTabKeyNavigation(False)
        self.TableWidget_tickers.setObjectName("TableWidget_tickers")
        self.TableWidget_tickers.setColumnCount(3)
        self.TableWidget_tickers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_tickers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_tickers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_tickers.setHorizontalHeaderItem(2, item)
        self.TableWidget_tickers.verticalHeader().setVisible(False)
        self.TabWidget_data.addTab(self.tab_ticker, "")
        self.tab_price = QtWidgets.QWidget()
        self.tab_price.setObjectName("tab_price")
        self.TableWidget_prices = QtWidgets.QTableWidget(self.tab_price)
        self.TableWidget_prices.setGeometry(QtCore.QRect(30, 60, 231, 321))
        self.TableWidget_prices.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TableWidget_prices.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TableWidget_prices.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TableWidget_prices.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TableWidget_prices.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.TableWidget_prices.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TableWidget_prices.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TableWidget_prices.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TableWidget_prices.setGridStyle(QtCore.Qt.DashLine)
        self.TableWidget_prices.setObjectName("TableWidget_prices")
        self.TableWidget_prices.setColumnCount(2)
        self.TableWidget_prices.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.TableWidget_prices.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.TableWidget_prices.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(9, 0, item)
        self.TabWidget_data.addTab(self.tab_price, "")
        self.GroupBox_order = QtWidgets.QGroupBox(Console)
        self.GroupBox_order.setGeometry(QtCore.QRect(700, 10, 311, 111))
        self.GroupBox_order.setObjectName("GroupBox_order")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.GroupBox_order)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 291, 81))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_order = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_order.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_order.setObjectName("horizontalLayout_order")
        self.gridLayout_limit_order = QtWidgets.QGridLayout()
        self.gridLayout_limit_order.setObjectName("gridLayout_limit_order")
        self.horizontalLayout_limit_price = QtWidgets.QHBoxLayout()
        self.horizontalLayout_limit_price.setObjectName("horizontalLayout_limit_price")
        self.Label_limit_price = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.Label_limit_price.setObjectName("Label_limit_price")
        self.horizontalLayout_limit_price.addWidget(self.Label_limit_price)
        self.Edit_limit_price = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.Edit_limit_price.setObjectName("Edit_limit_price")
        self.horizontalLayout_limit_price.addWidget(self.Edit_limit_price)
        self.gridLayout_limit_order.addLayout(self.horizontalLayout_limit_price, 0, 0, 1, 1)
        self.horizontalLayout_longshort = QtWidgets.QHBoxLayout()
        self.horizontalLayout_longshort.setObjectName("horizontalLayout_longshort")
        self.Button_long = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.Button_long.setObjectName("Button_long")
        self.horizontalLayout_longshort.addWidget(self.Button_long)
        self.Button_short = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.Button_short.setObjectName("Button_short")
        self.horizontalLayout_longshort.addWidget(self.Button_short)
        self.gridLayout_limit_order.addLayout(self.horizontalLayout_longshort, 1, 0, 1, 1)
        self.horizontalLayout_order.addLayout(self.gridLayout_limit_order)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_order.addItem(spacerItem)
        self.verticalLayout_market_order = QtWidgets.QVBoxLayout()
        self.verticalLayout_market_order.setObjectName("verticalLayout_market_order")
        self.Button_market_long = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.Button_market_long.setObjectName("Button_market_long")
        self.verticalLayout_market_order.addWidget(self.Button_market_long)
        self.Button_market_short = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.Button_market_short.setObjectName("Button_market_short")
        self.verticalLayout_market_order.addWidget(self.Button_market_short)
        self.horizontalLayout_order.addLayout(self.verticalLayout_market_order)
        self.GroupBox_resample = QtWidgets.QGroupBox(Console)
        self.GroupBox_resample.setGeometry(QtCore.QRect(10, 10, 231, 81))
        self.GroupBox_resample.setObjectName("GroupBox_resample")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.GroupBox_resample)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 211, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HBoxLayout_resample = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HBoxLayout_resample.setContentsMargins(0, 0, 0, 0)
        self.HBoxLayout_resample.setObjectName("HBoxLayout_resample")
        self.RadioButton_min_1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_min_1.setChecked(True)
        self.RadioButton_min_1.setObjectName("RadioButton_min_1")
        self.HBoxLayout_resample.addWidget(self.RadioButton_min_1)
        self.RadioButton_min_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_min_5.setObjectName("RadioButton_min_5")
        self.HBoxLayout_resample.addWidget(self.RadioButton_min_5)
        self.RadioButton_min_10 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_min_10.setObjectName("RadioButton_min_10")
        self.HBoxLayout_resample.addWidget(self.RadioButton_min_10)
        self.RadioButton_min_30 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.RadioButton_min_30.setObjectName("RadioButton_min_30")
        self.HBoxLayout_resample.addWidget(self.RadioButton_min_30)
        self.GroupBox_goto = QtWidgets.QGroupBox(Console)
        self.GroupBox_goto.setGeometry(QtCore.QRect(250, 10, 421, 80))
        self.GroupBox_goto.setObjectName("GroupBox_goto")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.GroupBox_goto)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 311, 54))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_his = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_his.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_his.setObjectName("horizontalLayout_his")
        self.verticalLayout_from_to = QtWidgets.QVBoxLayout()
        self.verticalLayout_from_to.setObjectName("verticalLayout_from_to")
        self.horizontalLayout_from = QtWidgets.QHBoxLayout()
        self.horizontalLayout_from.setObjectName("horizontalLayout_from")
        self.Label_from = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Label_from.setObjectName("Label_from")
        self.horizontalLayout_from.addWidget(self.Label_from)
        self.DateTimeEdit_start = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget_2)
        self.DateTimeEdit_start.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.DateTimeEdit_start.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateTimeEdit_start.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.DateTimeEdit_start.setCalendarPopup(True)
        self.DateTimeEdit_start.setObjectName("DateTimeEdit_start")
        self.horizontalLayout_from.addWidget(self.DateTimeEdit_start)
        self.verticalLayout_from_to.addLayout(self.horizontalLayout_from)
        self.horizontalLayout_to = QtWidgets.QHBoxLayout()
        self.horizontalLayout_to.setObjectName("horizontalLayout_to")
        self.label_to = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_to.setObjectName("label_to")
        self.horizontalLayout_to.addWidget(self.label_to)
        self.DateTimeEdit_end = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget_2)
        self.DateTimeEdit_end.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.DateTimeEdit_end.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.DateTimeEdit_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 3, 20), QtCore.QTime(0, 0, 0)))
        self.DateTimeEdit_end.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.DateTimeEdit_end.setCalendarPopup(True)
        self.DateTimeEdit_end.setObjectName("DateTimeEdit_end")
        self.horizontalLayout_to.addWidget(self.DateTimeEdit_end)
        self.verticalLayout_from_to.addLayout(self.horizontalLayout_to)
        self.horizontalLayout_his.addLayout(self.verticalLayout_from_to)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_his.addItem(spacerItem1)
        self.Button_history = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_history.setFont(font)
        self.Button_history.setObjectName("Button_history")
        self.horizontalLayout_his.addWidget(self.Button_history)
        self.Button_current = QtWidgets.QPushButton(self.GroupBox_goto)
        self.Button_current.setGeometry(QtCore.QRect(330, 30, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_current.setFont(font)
        self.Button_current.setObjectName("Button_current")
        self.Label_limit_price.setBuddy(self.Edit_limit_price)

        self.retranslateUi(Console)
        self.TabWidget_data.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Console)

    def retranslateUi(self, Console):
        _translate = QtCore.QCoreApplication.translate
        Console.setWindowTitle(_translate("Console", "实盘交互console"))
        item = self.TableWidget_tickers.horizontalHeaderItem(0)
        item.setText(_translate("Console", "time"))
        item = self.TableWidget_tickers.horizontalHeaderItem(1)
        item.setText(_translate("Console", "price"))
        item = self.TableWidget_tickers.horizontalHeaderItem(2)
        item.setText(_translate("Console", "qty"))
        self.TabWidget_data.setTabText(self.TabWidget_data.indexOf(self.tab_ticker), _translate("Console", "Tickers"))
        item = self.TableWidget_prices.verticalHeaderItem(0)
        item.setText(_translate("Console", "卖⑤"))
        item = self.TableWidget_prices.verticalHeaderItem(1)
        item.setText(_translate("Console", "卖④"))
        item = self.TableWidget_prices.verticalHeaderItem(2)
        item.setText(_translate("Console", "卖③"))
        item = self.TableWidget_prices.verticalHeaderItem(3)
        item.setText(_translate("Console", "卖②"))
        item = self.TableWidget_prices.verticalHeaderItem(4)
        item.setText(_translate("Console", "卖①"))
        item = self.TableWidget_prices.verticalHeaderItem(5)
        item.setText(_translate("Console", "买①"))
        item = self.TableWidget_prices.verticalHeaderItem(6)
        item.setText(_translate("Console", "买②"))
        item = self.TableWidget_prices.verticalHeaderItem(7)
        item.setText(_translate("Console", "买④"))
        item = self.TableWidget_prices.verticalHeaderItem(8)
        item.setText(_translate("Console", "买③"))
        item = self.TableWidget_prices.verticalHeaderItem(9)
        item.setText(_translate("Console", "买⑤"))
        item = self.TableWidget_prices.horizontalHeaderItem(0)
        item.setText(_translate("Console", "Price"))
        item = self.TableWidget_prices.horizontalHeaderItem(1)
        item.setText(_translate("Console", "Qty"))
        __sortingEnabled = self.TableWidget_prices.isSortingEnabled()
        self.TableWidget_prices.setSortingEnabled(False)
        self.TableWidget_prices.setSortingEnabled(__sortingEnabled)
        self.TabWidget_data.setTabText(self.TabWidget_data.indexOf(self.tab_price), _translate("Console", "Price"))
        self.GroupBox_order.setTitle(_translate("Console", "AddOrder"))
        self.Label_limit_price.setText(_translate("Console", "Price："))
        self.Button_long.setText(_translate("Console", "Long"))
        self.Button_short.setText(_translate("Console", "Short"))
        self.Button_market_long.setText(_translate("Console", "Market Long"))
        self.Button_market_short.setText(_translate("Console", "Market Short"))
        self.GroupBox_resample.setTitle(_translate("Console", "resample"))
        self.RadioButton_min_1.setText(_translate("Console", "1m"))
        self.RadioButton_min_5.setText(_translate("Console", "5m"))
        self.RadioButton_min_10.setText(_translate("Console", "10m"))
        self.RadioButton_min_30.setText(_translate("Console", "30m"))
        self.GroupBox_goto.setTitle(_translate("Console", "goto"))
        self.Label_from.setText(_translate("Console", "From:"))
        self.DateTimeEdit_start.setDisplayFormat(_translate("Console", "M/d dddd H:mm"))
        self.label_to.setText(_translate("Console", "to  :"))
        self.DateTimeEdit_end.setDisplayFormat(_translate("Console", "M/d dddd H:mm"))
        self.Button_history.setText(_translate("Console", "History Review"))
        self.Button_current.setText(_translate("Console", "Current Market"))

from pyqtgraph.console import ConsoleWidget
