# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'console.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Console(object):
    def setupUi(self, Console):
        Console.setObjectName("Console")
        Console.resize(979, 656)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Console)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.GroupBox_resample = QtWidgets.QGroupBox(Console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox_resample.sizePolicy().hasHeightForWidth())
        self.GroupBox_resample.setSizePolicy(sizePolicy)
        self.GroupBox_resample.setMinimumSize(QtCore.QSize(190, 80))
        self.GroupBox_resample.setMaximumSize(QtCore.QSize(250, 90))
        self.GroupBox_resample.setObjectName("GroupBox_resample")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.GroupBox_resample)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.HBoxLayout_resample = QtWidgets.QHBoxLayout()
        self.HBoxLayout_resample.setObjectName("HBoxLayout_resample")
        self.RadioButton_min_1 = QtWidgets.QRadioButton(self.GroupBox_resample)
        self.RadioButton_min_1.setChecked(True)
        self.RadioButton_min_1.setObjectName("RadioButton_min_1")
        self.HBoxLayout_resample.addWidget(self.RadioButton_min_1)
        self.RadioButton_min_5 = QtWidgets.QRadioButton(self.GroupBox_resample)
        self.RadioButton_min_5.setObjectName("RadioButton_min_5")
        self.HBoxLayout_resample.addWidget(self.RadioButton_min_5)
        self.RadioButton_min_10 = QtWidgets.QRadioButton(self.GroupBox_resample)
        self.RadioButton_min_10.setObjectName("RadioButton_min_10")
        self.HBoxLayout_resample.addWidget(self.RadioButton_min_10)
        self.RadioButton_min_30 = QtWidgets.QRadioButton(self.GroupBox_resample)
        self.RadioButton_min_30.setObjectName("RadioButton_min_30")
        self.HBoxLayout_resample.addWidget(self.RadioButton_min_30)
        self.verticalLayout_3.addLayout(self.HBoxLayout_resample)
        self.horizontalLayout_2.addWidget(self.GroupBox_resample)
        self.GroupBox_goto = QtWidgets.QGroupBox(Console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupBox_goto.sizePolicy().hasHeightForWidth())
        self.GroupBox_goto.setSizePolicy(sizePolicy)
        self.GroupBox_goto.setMinimumSize(QtCore.QSize(440, 80))
        self.GroupBox_goto.setMaximumSize(QtCore.QSize(16777215, 90))
        self.GroupBox_goto.setObjectName("GroupBox_goto")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.GroupBox_goto)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_his = QtWidgets.QHBoxLayout()
        self.horizontalLayout_his.setObjectName("horizontalLayout_his")
        self.verticalLayout_from_to = QtWidgets.QVBoxLayout()
        self.verticalLayout_from_to.setObjectName("verticalLayout_from_to")
        self.horizontalLayout_from = QtWidgets.QHBoxLayout()
        self.horizontalLayout_from.setObjectName("horizontalLayout_from")
        self.Label_from = QtWidgets.QLabel(self.GroupBox_goto)
        self.Label_from.setObjectName("Label_from")
        self.horizontalLayout_from.addWidget(self.Label_from)
        self.DateTimeEdit_start = QtWidgets.QDateTimeEdit(self.GroupBox_goto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DateTimeEdit_start.sizePolicy().hasHeightForWidth())
        self.DateTimeEdit_start.setSizePolicy(sizePolicy)
        self.DateTimeEdit_start.setMinimumSize(QtCore.QSize(130, 18))
        self.DateTimeEdit_start.setMaximumSize(QtCore.QSize(16777215, 25))
        self.DateTimeEdit_start.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.DateTimeEdit_start.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateTimeEdit_start.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.DateTimeEdit_start.setCalendarPopup(True)
        self.DateTimeEdit_start.setObjectName("DateTimeEdit_start")
        self.horizontalLayout_from.addWidget(self.DateTimeEdit_start)
        self.verticalLayout_from_to.addLayout(self.horizontalLayout_from)
        self.horizontalLayout_to = QtWidgets.QHBoxLayout()
        self.horizontalLayout_to.setObjectName("horizontalLayout_to")
        self.label_to = QtWidgets.QLabel(self.GroupBox_goto)
        self.label_to.setObjectName("label_to")
        self.horizontalLayout_to.addWidget(self.label_to)
        self.DateTimeEdit_end = QtWidgets.QDateTimeEdit(self.GroupBox_goto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DateTimeEdit_end.sizePolicy().hasHeightForWidth())
        self.DateTimeEdit_end.setSizePolicy(sizePolicy)
        self.DateTimeEdit_end.setMinimumSize(QtCore.QSize(130, 18))
        self.DateTimeEdit_end.setMaximumSize(QtCore.QSize(16777215, 25))
        self.DateTimeEdit_end.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.DateTimeEdit_end.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.DateTimeEdit_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 3, 20), QtCore.QTime(0, 0, 0)))
        self.DateTimeEdit_end.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.DateTimeEdit_end.setCalendarPopup(True)
        self.DateTimeEdit_end.setObjectName("DateTimeEdit_end")
        self.horizontalLayout_to.addWidget(self.DateTimeEdit_end)
        self.verticalLayout_from_to.addLayout(self.horizontalLayout_to)
        self.horizontalLayout_his.addLayout(self.verticalLayout_from_to)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_his.addItem(spacerItem)
        self.Button_history = QtWidgets.QPushButton(self.GroupBox_goto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_history.sizePolicy().hasHeightForWidth())
        self.Button_history.setSizePolicy(sizePolicy)
        self.Button_history.setMinimumSize(QtCore.QSize(90, 20))
        self.Button_history.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_history.setFont(font)
        self.Button_history.setObjectName("Button_history")
        self.horizontalLayout_his.addWidget(self.Button_history)
        self.horizontalLayout.addLayout(self.horizontalLayout_his)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        self.Button_current = QtWidgets.QPushButton(self.GroupBox_goto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_current.sizePolicy().hasHeightForWidth())
        self.Button_current.setSizePolicy(sizePolicy)
        self.Button_current.setMinimumSize(QtCore.QSize(90, 20))
        self.Button_current.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_current.setFont(font)
        self.Button_current.setObjectName("Button_current")
        self.horizontalLayout.addWidget(self.Button_current)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.GroupBox_goto)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.ConsoleWidget_con = ConsoleWidget(Console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConsoleWidget_con.sizePolicy().hasHeightForWidth())
        self.ConsoleWidget_con.setSizePolicy(sizePolicy)
        self.ConsoleWidget_con.setMinimumSize(QtCore.QSize(630, 300))
        self.ConsoleWidget_con.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ConsoleWidget_con.setObjectName("ConsoleWidget_con")
        self.verticalLayout_5.addWidget(self.ConsoleWidget_con)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 2, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.TabWidget_data = QtWidgets.QTabWidget(Console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabWidget_data.sizePolicy().hasHeightForWidth())
        self.TabWidget_data.setSizePolicy(sizePolicy)
        self.TabWidget_data.setMinimumSize(QtCore.QSize(311, 370))
        self.TabWidget_data.setObjectName("TabWidget_data")
        self.tab_ticker = QtWidgets.QWidget()
        self.tab_ticker.setObjectName("tab_ticker")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_ticker)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TableWidget_tickers = QtWidgets.QTableWidget(self.tab_ticker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget_tickers.sizePolicy().hasHeightForWidth())
        self.TableWidget_tickers.setSizePolicy(sizePolicy)
        self.TableWidget_tickers.setMinimumSize(QtCore.QSize(296, 327))
        self.TableWidget_tickers.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TableWidget_tickers.setAutoScroll(False)
        self.TableWidget_tickers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TableWidget_tickers.setTabKeyNavigation(False)
        self.TableWidget_tickers.setObjectName("TableWidget_tickers")
        self.TableWidget_tickers.setColumnCount(3)
        self.TableWidget_tickers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_tickers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_tickers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_tickers.setHorizontalHeaderItem(2, item)
        self.TableWidget_tickers.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.TableWidget_tickers)
        self.TabWidget_data.addTab(self.tab_ticker, "")
        self.tab_price = QtWidgets.QWidget()
        self.tab_price.setObjectName("tab_price")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_price)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TableWidget_prices = QtWidgets.QTableWidget(self.tab_price)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget_prices.sizePolicy().hasHeightForWidth())
        self.TableWidget_prices.setSizePolicy(sizePolicy)
        self.TableWidget_prices.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TableWidget_prices.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TableWidget_prices.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TableWidget_prices.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TableWidget_prices.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.TableWidget_prices.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TableWidget_prices.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TableWidget_prices.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TableWidget_prices.setGridStyle(QtCore.Qt.DashLine)
        self.TableWidget_prices.setObjectName("TableWidget_prices")
        self.TableWidget_prices.setColumnCount(2)
        self.TableWidget_prices.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.TableWidget_prices.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.TableWidget_prices.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_prices.setItem(9, 0, item)
        self.TableWidget_prices.horizontalHeader().setDefaultSectionSize(125)
        self.TableWidget_prices.horizontalHeader().setStretchLastSection(True)
        self.TableWidget_prices.verticalHeader().setDefaultSectionSize(45)
        self.verticalLayout_2.addWidget(self.TableWidget_prices)
        self.TabWidget_data.addTab(self.tab_price, "")
        self.verticalLayout_6.addWidget(self.TabWidget_data)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(308, 108, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)

        self.retranslateUi(Console)
        self.TabWidget_data.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Console)

    def retranslateUi(self, Console):
        _translate = QtCore.QCoreApplication.translate
        Console.setWindowTitle(_translate("Console", "实盘交互console"))
        self.GroupBox_resample.setTitle(_translate("Console", "resample"))
        self.RadioButton_min_1.setText(_translate("Console", "1m"))
        self.RadioButton_min_5.setText(_translate("Console", "5m"))
        self.RadioButton_min_10.setText(_translate("Console", "10m"))
        self.RadioButton_min_30.setText(_translate("Console", "30m"))
        self.GroupBox_goto.setTitle(_translate("Console", "goto"))
        self.Label_from.setText(_translate("Console", "From:"))
        self.DateTimeEdit_start.setDisplayFormat(_translate("Console", "M/d dddd H:mm"))
        self.label_to.setText(_translate("Console", "to  :"))
        self.DateTimeEdit_end.setDisplayFormat(_translate("Console", "M/d dddd H:mm"))
        self.Button_history.setText(_translate("Console", "History Review"))
        self.Button_current.setText(_translate("Console", "Current Market"))
        item = self.TableWidget_tickers.horizontalHeaderItem(0)
        item.setText(_translate("Console", "time"))
        item = self.TableWidget_tickers.horizontalHeaderItem(1)
        item.setText(_translate("Console", "price"))
        item = self.TableWidget_tickers.horizontalHeaderItem(2)
        item.setText(_translate("Console", "qty"))
        self.TabWidget_data.setTabText(self.TabWidget_data.indexOf(self.tab_ticker), _translate("Console", "Tickers"))
        item = self.TableWidget_prices.verticalHeaderItem(0)
        item.setText(_translate("Console", "卖⑤"))
        item = self.TableWidget_prices.verticalHeaderItem(1)
        item.setText(_translate("Console", "卖④"))
        item = self.TableWidget_prices.verticalHeaderItem(2)
        item.setText(_translate("Console", "卖③"))
        item = self.TableWidget_prices.verticalHeaderItem(3)
        item.setText(_translate("Console", "卖②"))
        item = self.TableWidget_prices.verticalHeaderItem(4)
        item.setText(_translate("Console", "卖①"))
        item = self.TableWidget_prices.verticalHeaderItem(5)
        item.setText(_translate("Console", "买①"))
        item = self.TableWidget_prices.verticalHeaderItem(6)
        item.setText(_translate("Console", "买②"))
        item = self.TableWidget_prices.verticalHeaderItem(7)
        item.setText(_translate("Console", "买④"))
        item = self.TableWidget_prices.verticalHeaderItem(8)
        item.setText(_translate("Console", "买③"))
        item = self.TableWidget_prices.verticalHeaderItem(9)
        item.setText(_translate("Console", "买⑤"))
        item = self.TableWidget_prices.horizontalHeaderItem(0)
        item.setText(_translate("Console", "Price"))
        item = self.TableWidget_prices.horizontalHeaderItem(1)
        item.setText(_translate("Console", "Qty"))
        __sortingEnabled = self.TableWidget_prices.isSortingEnabled()
        self.TableWidget_prices.setSortingEnabled(False)
        self.TableWidget_prices.setSortingEnabled(__sortingEnabled)
        self.TabWidget_data.setTabText(self.TabWidget_data.indexOf(self.tab_price), _translate("Console", "Price"))

from pyqtgraph.console import ConsoleWidget
