# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(1200, 30))
        self.widget.setObjectName("widget")
        self.comboBox = ComboCheckBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(630, 0, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(720, 0, 493, 27))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_Trade_Data = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_Trade_Data.setChecked(True)
        self.checkBox_Trade_Data.setObjectName("checkBox_Trade_Data")
        self.horizontalLayout_2.addWidget(self.checkBox_Trade_Data)
        self.checkBox_MACD_HL_MARK = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_MACD_HL_MARK.setChecked(True)
        self.checkBox_MACD_HL_MARK.setObjectName("checkBox_MACD_HL_MARK")
        self.horizontalLayout_2.addWidget(self.checkBox_MACD_HL_MARK)
        self.checkBox_MACD = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_MACD.setChecked(True)
        self.checkBox_MACD.setObjectName("checkBox_MACD")
        self.horizontalLayout_2.addWidget(self.checkBox_MACD)
        self.checkBox_STD = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_STD.setChecked(True)
        self.checkBox_STD.setObjectName("checkBox_STD")
        self.horizontalLayout_2.addWidget(self.checkBox_STD)
        self.checkBox_MA = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_MA.setChecked(True)
        self.checkBox_MA.setObjectName("checkBox_MA")
        self.horizontalLayout_2.addWidget(self.checkBox_MA)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_order = QtWidgets.QPushButton(self.widget1)
        self.pushButton_order.setObjectName("pushButton_order")
        self.horizontalLayout.addWidget(self.pushButton_order)
        self.pushButton_console = QtWidgets.QPushButton(self.widget1)
        self.pushButton_console.setObjectName("pushButton_console")
        self.horizontalLayout.addWidget(self.pushButton_console)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.widget)
        self.QVBoxLayout_ohlc = QtWidgets.QVBoxLayout()
        self.QVBoxLayout_ohlc.setObjectName("QVBoxLayout_ohlc")
        self.QWidget_ohlc = OHlCWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QWidget_ohlc.sizePolicy().hasHeightForWidth())
        self.QWidget_ohlc.setSizePolicy(sizePolicy)
        self.QWidget_ohlc.setMinimumSize(QtCore.QSize(400, 400))
        self.QWidget_ohlc.setObjectName("QWidget_ohlc")
        self.QVBoxLayout_ohlc.addWidget(self.QWidget_ohlc)
        self.verticalLayout.addLayout(self.QVBoxLayout_ohlc)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_Trade_Data.setText(_translate("MainWindow", "Trade_Data"))
        self.checkBox_MACD_HL_MARK.setText(_translate("MainWindow", "MACD_HL_MARK"))
        self.checkBox_MACD.setText(_translate("MainWindow", "MACD"))
        self.checkBox_STD.setText(_translate("MainWindow", "STD"))
        self.checkBox_MA.setText(_translate("MainWindow", "MA"))
        self.pushButton_order.setText(_translate("MainWindow", "order"))
        self.pushButton_console.setText(_translate("MainWindow", "console"))

from data_visualize.OHLC_ui import OHlCWidget
from data_visualize.baseitems import ComboCheckBox
